# Generated by Django 5.2.8 on 2025-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_barcodes',
            field=models.JSONField(blank=True, default=list, help_text='Additional barcodes for the same product (supports multiple barcodes per product)'),
        ),

    ]
