# Generated by Django 5.2.8 on 2025-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_wastebatch_waste_shop_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Primary barcode for scanning during sales', max_length=100),
        ),
    ]
