# Generated by Django 5.2.8 on 2025-12-27 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for refund', max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded to customer', max_digits=10)),
                ('refund_reason', models.CharField(choices=[('Damaged Product', 'Damaged Product'), ('Wrong Item', 'Wrong Item'), ('Customer Request', 'Customer Request'), ('Quality Issue', 'Quality Issue'), ('Expired Product', 'Expired Product'), ('Price Error', 'Price Error'), ('Other', 'Other')], max_length=30)),
                ('refund_type', models.CharField(choices=[('money', 'Money Refund'), ('stock', 'Stock Return')], default='money', max_length=10)),
                ('return_stock', models.BooleanField(default=False, help_text='Whether this refund involves returning stock to inventory')),
                ('return_items', models.JSONField(blank=True, default=list, help_text='List of returned items with quantities')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Rent & Utilities', 'Rent & Utilities'), ('Office Supplies', 'Office Supplies'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Professional Services', 'Professional Services'), ('Insurance', 'Insurance'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Transportation', 'Transportation'), ('Bank Fees', 'Bank Fees'), ('Taxes', 'Taxes'), ('Employee Expenses', 'Employee Expenses'), ('Equipment Purchase', 'Equipment Purchase'), ('Software & Subscriptions', 'Software & Subscriptions'), ('Travel & Entertainment', 'Travel & Entertainment'), ('Mortgage Payments', 'Mortgage Payments'), ('School Fees', 'School Fees'), ('Medical Expenses', 'Medical Expenses'), ('Other', 'Other')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when expense occurred'),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt or invoice number', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor or payee name', max_length=255),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['shop', '-created_at'], name='core_expens_shop_id_7eab8f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', '-created_at'], name='core_expens_categor_59140f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='core_expens_expense_9af794_idx'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier'),
        ),
        migrations.AddField(
            model_name='refund',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Original sale this refund relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sale'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['shop', '-created_at'], name='core_refund_shop_id_5d6f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_type', '-created_at'], name='core_refund_refund__483628_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_reason'], name='core_refund_refund__f54b3c_idx'),
        ),
    ]
