# Generated by Django 5.2.8 on 2025-12-27 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_refund_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Associated product for staff lunch or product expense', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='expense',
            name='product_barcode',
            field=models.CharField(blank=True, help_text='Product barcode at time of expense', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='product_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product cost price at time of expense', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='product_line_code',
            field=models.CharField(blank=True, help_text='Product line code at time of expense', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name at time of expense', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Staff Lunch', 'Staff Lunch'), ('Product Expense', 'Product Expense')], default='Product Expense', max_length=50),
        ),
    ]
