# Generated by Django 5.2.8 on 2025-12-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_update_expense_categories_and_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity for staff lunch', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='staff_lunch_type',
            field=models.CharField(choices=[('stock', 'Eat from Stock'), ('money', 'Money Allowance')], default='stock', help_text='Type of staff lunch', max_length=20),
        ),
    ]
