# Generated by Django 5.2.8 on 2025-12-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_staff_lunch_fields_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='balance_status',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('unbalanced', 'Unbalanced'), ('pending', 'Pending')], default='pending', help_text='Whether stock take is balanced or not', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='exact_match_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of products that matched exactly'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for failure if stock take failed'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='overstock_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of products with overstock'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='stock_take_type',
            field=models.CharField(choices=[('weekly', 'Weekly Stock Take'), ('monthly', 'Monthly Stock Take')], default='weekly', help_text='Type of stock take: weekly or monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='understock_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of products with understock'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
