// Navigation route names
export const ROUTES = {
  WELCOME: 'Welcome',
  REGISTER: 'Register',
  LOGIN: 'Login',
  CASHIER_DASHBOARD: 'CashierDashboard',
  FORGOT_PASSWORD: 'ForgotPassword',
  CASHIER_RESET_PASSWORD: 'CashierResetPassword',
  REGISTRATION_DETAILS: 'RegistrationDetails',
  SUCCESS: 'Success',
  OWNER_DASHBOARD: 'OwnerDashboard',
  SETTINGS: 'Settings',
  STAFF_MANAGEMENT: 'StaffManagement',
  STAFF_CONTRACT: 'StaffContract',
  CASHIER_REGISTER: 'CashierRegister',
  INVENTORY_AUDIT_TRAIL: 'InventoryAuditTrail',
  ORDER_CONFIRMATION: 'OrderConfirmation',
  INVENTORY_RECEIVING: 'InventoryReceiving',
  RESTOCK_MANAGER: 'RestockManager',
  STOCK_TRANSFER: 'StockTransfer',
  STOCK_TRANSFER_HISTORY: 'StockTransferHistory',
  STOCK_VALUATION: 'StockValuation',
  POS_PRICE: 'POSPrice',
  SALES_AND_REFUNDS: 'SalesAndRefunds',
  OWNER_SALES: 'OwnerSales',
  EXPENSE_MANAGEMENT: 'ExpenseManagement',
  STOCK_TAKE: 'StockTake',
  STOCK_TAKE_HISTORY: 'StockTakeHistory',
};

// Screen titles
export const SCREEN_TITLES = {
  [ROUTES.WELCOME]: 'Welcome',
  [ROUTES.REGISTER]: 'Create Shop',
  [ROUTES.LOGIN]: 'Sign In',
  [ROUTES.CASHIER_DASHBOARD]: 'Cashier Dashboard',
  [ROUTES.FORGOT_PASSWORD]: 'Forgot Password',
  [ROUTES.CASHIER_RESET_PASSWORD]: 'Cashier Password Reset',
  [ROUTES.REGISTRATION_DETAILS]: 'Registration Details',
  [ROUTES.SUCCESS]: 'Success',
  [ROUTES.OWNER_DASHBOARD]: 'Owner Dashboard',
  [ROUTES.SETTINGS]: 'Settings',
  [ROUTES.STAFF_MANAGEMENT]: 'Staff Management',
  [ROUTES.STAFF_CONTRACT]: 'Staff Contract',
  [ROUTES.CASHIER_REGISTER]: 'Staff Registration',
  [ROUTES.INVENTORY_AUDIT_TRAIL]: 'Inventory Audit Trail',
  [ROUTES.ORDER_CONFIRMATION]: 'Order Confirmation',
  [ROUTES.INVENTORY_RECEIVING]: 'Inventory Receiving',
  [ROUTES.RESTOCK_MANAGER]: 'Restock Manager',
  [ROUTES.STOCK_TRANSFER]: 'Stock Transfer',
  [ROUTES.STOCK_TRANSFER_HISTORY]: 'Transfer History',
  [ROUTES.STOCK_VALUATION]: 'Stock Valuation',
  [ROUTES.POS_PRICE]: 'POS Price Labels',
  [ROUTES.SALES_AND_REFUNDS]: 'Sales & Refunds',
  [ROUTES.OWNER_SALES]: 'Today\'s Sales',
  [ROUTES.EXPENSE_MANAGEMENT]: 'Expense Management',
  [ROUTES.STOCK_TAKE]: 'Stock Take Management',
  [ROUTES.STOCK_TAKE_HISTORY]: 'Stock Take History',
};